_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 55
                - 77
            "2":
                - 1
                - 55
                - 77
            "3":
                - 19
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": darwin-x86_64
beta:
    value: 1
epochs:
    value: 50
hidden_dim:
    value: 128
latent_dim:
    value: 32
learning_rate:
    value: 0.001
